Traceback (most recent call last):
  File "/home/y5luo/DSC180B_project/T5_SQuAD_Prompt_Tuning/run.py", line 200, in <module>
    main(args)
  File "/home/y5luo/DSC180B_project/T5_SQuAD_Prompt_Tuning/run.py", line 140, in main
    train(args)
  File "/home/y5luo/DSC180B_project/T5_SQuAD_Prompt_Tuning/run.py", line 127, in train
    trainer.train()
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1332, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1891, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/trainer.py", line 1923, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y5luo/DSC180B_project/T5_SQuAD_Prompt_Tuning/model.py", line 165, in forward
    return super().forward(
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1574, in forward
    encoder_outputs = self.encoder(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 1009, in forward
    layer_outputs = layer_module(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 644, in forward
    self_attention_outputs = self.layer[0](
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 551, in forward
    attention_output = self.SelfAttention(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/y5luo/.local/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py", line 514, in forward
    attn_weights = nn.functional.dropout(
  File "/opt/conda/lib/python3.9/site-packages/torch/nn/functional.py", line 1168, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
RuntimeError: CUDA out of memory. Tried to allocate 104.00 MiB (GPU 0; 23.65 GiB total capacity; 10.17 GiB already allocated; 5.31 MiB free; 10.46 GiB reserved in total by PyTorch)

